// ============================================
// TASKS PAGE - View and Complete Tasks
// ============================================
// This screen displays all tasks for today.
// Users can:
// - View all tasks with checkboxes
// - Mark tasks as completed/incomplete
// - Pull to refresh the list
// 
// Note: Tasks are stored locally (SharedPreferences), not in backend.
// Tasks are auto-generated daily from user's animals.
// ============================================

import 'package:farm/services/task_service.dart';
import 'package:flutter/material.dart';

/// TasksPage - Screen showing today's tasks
/// 
/// Flow:
/// 1. Screen opens → initState() calls _loadTasks()
/// 2. Loads today's tasks from local storage (SharedPreferences)
/// 3. Displays tasks in a scrollable list with checkboxes
/// 4. User can check/uncheck tasks to mark completion
/// 5. Completion status saved to local storage
/// 
/// Navigation:
/// - Back button → Previous screen (usually DashboardPage)
/// 
/// Accessed from:
/// - DashboardPage "View all" link in Tasks card
/// - DashboardPage Tasks icon (bottom nav)
/// 
/// Data Source:
/// - Tasks are loaded from SharedPreferences (local storage)
/// - Tasks are generated by DashboardPage based on user's animals
class TasksPage extends StatefulWidget {
  static const routeName = '/tasks';
  const TasksPage({super.key});

  @override
  State<TasksPage> createState() => _TasksPageState();
}

/// State class for TasksPage
/// Manages task list and completion status
class _TasksPageState extends State<TasksPage> {
  // ============================================
  // STATE VARIABLES
  // ============================================
  // List of tasks for today
  List<Task> _tasks = [];
  
  // Shows loading spinner while loading tasks
  bool _isLoading = true;

  /// Called when screen is first created
  /// 
  /// Flow:
  /// 1. Screen initializes
  /// 2. Immediately loads tasks from local storage
  @override
  void initState() {
    super.initState();
    _loadTasks();
  }

  /// Loads today's tasks from local storage
  /// 
  /// Flow:
  /// 1. Shows loading spinner
  /// 2. Calls TaskService.getTodayTasks() to load from SharedPreferences
  /// 3. Filters to only today's tasks
  /// 4. Updates UI with task list
  /// 
  /// Called by: initState(), pull-to-refresh, after task toggle
  Future<void> _loadTasks() async {
    setState(() => _isLoading = true); // Show spinner
    
    // Load tasks from local storage (SharedPreferences)
    // Only returns tasks for today's date
    final tasks = await TaskService.getTodayTasks();
    
    setState(() {
      _tasks = tasks; // Store task list
      _isLoading = false; // Hide spinner
    });
  }

  /// Toggles a task's completion status
  /// 
  /// Flow:
  /// 1. User checks/unchecks a task checkbox
  /// 2. Creates updated task with opposite completion status
  /// 3. Saves updated status to local storage
  /// 4. Reloads tasks to refresh UI
  /// 
  /// Called by: TaskCard checkbox onChanged
  /// 
  /// Parameters:
  /// - task: The task to toggle
  Future<void> _toggleTask(Task task) async {
    // Create new task with toggled completion status
    final updatedTask = task.copyWith(isCompleted: !task.isCompleted);
    
    // Save updated status to local storage
    await TaskService.updateTaskCompletion(task.id, updatedTask.isCompleted);
    
    // Reload tasks to refresh UI
    await _loadTasks();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFE4E7D6),
      appBar: AppBar(
        backgroundColor: const Color(0xFF2F7D32),
        foregroundColor: Colors.white,
        title: const Text(
          'Today\'s Tasks',
          style: TextStyle(fontWeight: FontWeight.bold),
        ),
        elevation: 0,
      ),
      body: _isLoading
          ? const Center(
              child: CircularProgressIndicator(
                valueColor: AlwaysStoppedAnimation<Color>(Color(0xFF2F7D32)),
              ),
            )
          : _tasks.isEmpty
              ? Center(
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Icon(
                        Icons.task_alt,
                        size: 64,
                        color: Colors.grey[400],
                      ),
                      const SizedBox(height: 16),
                      Text(
                        'No tasks for today',
                        style: TextStyle(
                          fontSize: 18,
                          color: Colors.grey[600],
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                      const SizedBox(height: 8),
                      Text(
                        'Add animals to generate tasks',
                        style: TextStyle(
                          fontSize: 14,
                          color: Colors.grey[500],
                        ),
                      ),
                    ],
                  ),
                )
              : RefreshIndicator(
                  onRefresh: _loadTasks,
                  color: const Color(0xFF2F7D32),
                  child: ListView.builder(
                    padding: const EdgeInsets.all(20),
                    itemCount: _tasks.length,
                    itemBuilder: (context, index) {
                      final task = _tasks[index];
                      return _TaskCard(
                        task: task,
                        onToggle: () => _toggleTask(task),
                      );
                    },
                  ),
                ),
    );
  }
}

/// TaskCard - Widget for displaying a single task
/// 
/// Shows:
/// - Checkbox for completion status
/// - Task title (with strikethrough if completed)
/// - Animal type badge
/// - Quantity (if more than 1)
/// - Completion icon
class _TaskCard extends StatelessWidget {
  /// The task to display
  final Task task;
  
  /// Callback when checkbox is toggled
  final VoidCallback onToggle;

  const _TaskCard({
    required this.task,
    required this.onToggle,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        boxShadow: [
          BoxShadow(
            color: Colors.grey.withOpacity(0.1),
            blurRadius: 8,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: ListTile(
        contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
        // ============================================
        // CHECKBOX - Task completion status
        // ============================================
        // User can tap to toggle completion
        leading: Checkbox(
          value: task.isCompleted, // Current completion status
          onChanged: (_) => onToggle(), // Toggle when tapped
          activeColor: const Color(0xFF2F7D32), // Green when checked
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(4),
          ),
        ),
        title: Text(
          task.title,
          style: TextStyle(
            fontSize: 16,
            fontWeight: FontWeight.w600,
            decoration: task.isCompleted
                ? TextDecoration.lineThrough
                : TextDecoration.none,
            color: task.isCompleted
                ? Colors.grey[600]
                : const Color(0xFF2F2F2F),
          ),
        ),
        subtitle: Padding(
          padding: const EdgeInsets.only(top: 4),
          child: Row(
            children: [
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                decoration: BoxDecoration(
                  color: const Color(0xFFE4E7D6),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Text(
                  task.animalType,
                  style: const TextStyle(
                    fontSize: 12,
                    color: Color(0xFF2F7D32),
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              if (task.quantity > 1) ...[
                const SizedBox(width: 8),
                Text(
                  'Qty: ${task.quantity}',
                  style: TextStyle(
                    fontSize: 12,
                    color: Colors.grey[600],
                  ),
                ),
              ],
            ],
          ),
        ),
        trailing: task.isCompleted
            ? const Icon(
                Icons.check_circle,
                color: Color(0xFF2F7D32),
                size: 24,
              )
            : const Icon(
                Icons.radio_button_unchecked,
                color: Colors.grey,
                size: 24,
              ),
      ),
    );
  }
}

